### ISSUE TITLE
Progress Bar Not Shown 

### ISSUE THREAD

**Issue by abhishek8506** [funOfheuristic/ResumableFileUploader#1]
All Uploading Process work fine ,except progress bar not shown .
![Screenshot 2020-11-06 at 2 13 40 PM](https://user-images.githubusercontent.com/34652662/98345177-50c1c400-203a-11eb-8efb-93b560ac71c4.png)
I think In Above screen Shot "uploadedBytes" value comes zero that why progress bar not shown ,Please help us to resolve

**Comment by funOfheuristic** [comment]
Thanks for raising the issue, it's resolved now, closing the same
